version: '3'

services:

  tracking:
    image: tracking
    build:
      context: .
      dockerfile: Tracking/Dockerfile
    depends_on:
    - distributed_cache
    - messages_middleware
    - event_sourcing_middleware
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - distributed_cache=distributed_cache
    - cache_db_vehicles=vehicles
    - messages_middleware=messages_middleware
    - middleware_exchange=platform
    - middleware_routes_subscriber=*.ping.vehicle
    - middleware_username=guest
    - middleware_password=guest
    - event_db_connection=Server=database_sql;Database=vehicle_events;User Id=sa;Password=Pass@word
    ports:
    - 32771:80

  vehicle:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
    - 32772:80


  customer:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
    - 32773:80

  ping:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
    - 32777:80
    depends_on:
    - distributed_cache
    - messages_middleware
    - event_sourcing_middleware
    - database_sql
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - distributed_cache=distributed_cache
    - cache_db_vehicles=vehicles
    - messages_middleware=messages_middleware
    - middleware_exchange=platform
    - middleware_ping_publisher=*.ping.vehicle
    - middleware_username=guest
    - middleware_password=guest

