version: '3'

services:

  ping:
    image: ping
    build:
      context: .
      dockerfile: Ping/Dockerfile
    depends_on:
    - distributed_cache
    - messages_middleware
    - eventsourcingmiddleware
    - database_sql
    environment:
    - distributed_cache=distributed_cache
    - cache_db_vehicles=vehicles
    - messages_middleware=messages_middleware
    - middleware_exchange=platform
    - middleware_info_publisher=info.ping.vehicle
    - middleware_username=guest
    - middleware_password=guest
    ports:
    - 32777:80

  distributed_cache:
    image: redis
    ports:
    - 5551:6739

  messages_middleware:
    image: rabbitmq
    ports:
    - 5552:5672
  
  database_sql:
    image: microsoft/mssql-server-linux:latest
    environment:
    - MSSQL_SA_PASSWORD=Pass@word
    - ACCEPT_EULA=Y
    - MSSQL_PID=Express
    ports:
    - 5553:1433

  tracking:
    image: tracking
    build:
      context: .
      dockerfile: Tracking/Dockerfile

  vehicle:
    image: vehicle
    build:
      context: .
      dockerfile: Vehicle/Dockerfile

  customer:
    image: customer
    build:
      context: .
      dockerfile: Customer/Dockerfile

  eventsourcingmiddleware:
    image: eventsourcingmiddleware
    build:
      context: .
      dockerfile: EventSourcingMiddleware/Dockerfile
    ports:
    - 32770:80
    depends_on:
    - messages_middleware
    - database_sql
    environment:
    - cache_db_vehicles=vehicles
    - messages_middleware=messages_middleware
    - middleware_exchange=platform
    - middleware_info_subscriber=info.ping.vehicle
    - middleware_username=guest
    - middleware_password=guest
    - event_db_connection=Server=database_sql;Database=vehicle_events;User Id=sa;Password=Pass@word